
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dbeats-backend-canary
spec:
  replicas: 1
  selector:
      matchLabels:
          app: dbeats
          role: backend
          env: canary
  template:
    metadata:
      name: backend
      labels:
        app: dbeats
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: abhishekhande/dbeats:imagepush
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080

